//! The notification-area icon.
//!
//! The only part of the program that is always on screen, and the answer to the
//! question a tray-resident application has to answer before anything else:
//! *how do I get at it if I have forgotten the shortcut.*
//!
//! # Why the events come back through a handler rather than a poll
//!
//! `tray-icon` and `muda` both publish their events on a global channel that a
//! caller is expected to drain. Draining it from the frame loop would work only
//! while there are frames - and this program's whole design is that a hidden
//! panel asks for none at all, so a tray click would sit in that channel until
//! something else happened to wake the process. Which is to say: until the user
//! did the thing they were trying to avoid doing.
//!
//! So both crates are given a handler instead, and the handler does what every
//! other producer in this program does - posts and then wakes. That is
//! [`crate::app::event::Events`] again, for the same reason it exists at all.

#![cfg(windows)]

use std::sync::Arc;

use muda::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder, TrayIconEvent};

/// The icon, at 32x32, as raw premultiplied-free RGBA.
///
/// Generated by `tools/make_icon.py` alongside `assets/files.ico`, and embedded
/// rather than read from disk: a tray icon that fails to appear because an
/// installer put a file somewhere else is a program that looks like it did not
/// start.
const ICON_RGBA: &[u8] = include_bytes!("../../assets/files-32.rgba");
const ICON_SIZE: u32 = 32;

/// What the user picked.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayAction {
    /// Bring the panel up. Also what a left-click on the icon means.
    Show,
    Help,
    Settings,
    Diagnostics,
    Quit,
}

/// The icon, its menu, and the ids that say which item was chosen.
///
/// Held for the life of the process: dropping a `TrayIcon` removes it from the
/// notification area, so a `let _ = ...` here would produce an icon that
/// flickers into existence and disappears.
pub struct Tray {
    _icon: TrayIcon,
    _menu: Menu,
    /// Kept for the test below, which is the only thing that reads them: the
    /// handler owns its own copy, because it outlives this struct's borrow.
    #[cfg_attr(not(test), allow(dead_code))]
    ids: Vec<(muda::MenuId, TrayAction)>,
}

impl Tray {
    /// Builds the icon and starts listening.
    ///
    /// `wake` is called after an event is recorded, and is the whole reason
    /// this is not a poll - see the module note.
    pub fn new(
        wake: impl Fn(TrayAction) + Send + Sync + 'static,
    ) -> Result<Self, Box<dyn std::error::Error>> {
        let menu = Menu::new();
        let show = MenuItem::new("Show files", true, None);
        let help = MenuItem::new("Keyboard shortcuts", true, None);
        let settings = MenuItem::new("Settings", true, None);
        let diagnostics = MenuItem::new("Diagnostics", true, None);
        let quit = MenuItem::new("Quit files", true, None);
        menu.append_items(&[
            &show,
            &PredefinedMenuItem::separator(),
            &help,
            &settings,
            &diagnostics,
            &PredefinedMenuItem::separator(),
            &quit,
        ])?;

        let ids = vec![
            (show.id().clone(), TrayAction::Show),
            (help.id().clone(), TrayAction::Help),
            (settings.id().clone(), TrayAction::Settings),
            (diagnostics.id().clone(), TrayAction::Diagnostics),
            (quit.id().clone(), TrayAction::Quit),
        ];

        let icon = TrayIconBuilder::new()
            .with_menu(Box::new(menu.clone()))
            // Named, because this is what the user sees when they hover over an
            // icon they do not recognise at half past four on a Friday.
            .with_tooltip("files - search job codes")
            .with_icon(Icon::from_rgba(ICON_RGBA.to_vec(), ICON_SIZE, ICON_SIZE)?)
            // The menu belongs on the right button only. A left-click that
            // opens a menu is a left-click that does not open the thing the
            // icon is for.
            .with_menu_on_left_click(false)
            .build()?;

        let wake = Arc::new(wake);

        // A left-click, or a double-click, means "show me the panel" - the same
        // as the shortcut, because somebody reaching for the tray icon has by
        // definition not used the shortcut.
        {
            let wake = Arc::clone(&wake);
            TrayIconEvent::set_event_handler(Some(move |event: TrayIconEvent| {
                let clicked = matches!(
                    event,
                    TrayIconEvent::Click {
                        button: tray_icon::MouseButton::Left,
                        button_state: tray_icon::MouseButtonState::Up,
                        ..
                    } | TrayIconEvent::DoubleClick {
                        button: tray_icon::MouseButton::Left,
                        ..
                    }
                );
                if clicked {
                    wake(TrayAction::Show);
                }
            }));
        }

        {
            let wake = Arc::clone(&wake);
            let ids = ids.clone();
            MenuEvent::set_event_handler(Some(move |event: MenuEvent| {
                if let Some((_, action)) = ids.iter().find(|(id, _)| *id == event.id) {
                    wake(*action);
                }
            }));
        }

        Ok(Self {
            _icon: icon,
            _menu: menu,
            ids,
        })
    }

    /// How many items the menu offers. For the test below, and for nothing
    /// else.
    #[cfg(test)]
    fn len(&self) -> usize {
        self.ids.len()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The icon is embedded, so a wrong length is a build that ships a tray
    /// icon made of whatever happened to be in the file - and `Icon::from_rgba`
    /// would reject it at run time, which is to say in front of the user.
    #[test]
    fn the_embedded_icon_is_the_size_it_claims_to_be() {
        assert_eq!(
            ICON_RGBA.len(),
            (ICON_SIZE * ICON_SIZE * 4) as usize,
            "assets/files-32.rgba does not match ICON_SIZE - re-run tools/make_icon.py"
        );
    }

    /// It must also be an icon rather than a transparent square, which is what
    /// a generator that silently drew nothing would produce.
    #[test]
    fn the_embedded_icon_is_not_blank() {
        let opaque = ICON_RGBA.chunks_exact(4).filter(|p| p[3] > 0).count();
        let total = ICON_RGBA.len() / 4;
        assert!(
            opaque > total / 2,
            "only {opaque} of {total} pixels are drawn"
        );

        // And it has the two tones the design calls for - a flat square would
        // pass the test above.
        let mut colours: Vec<[u8; 3]> = ICON_RGBA
            .chunks_exact(4)
            .filter(|p| p[3] == 255)
            .map(|p| [p[0], p[1], p[2]])
            .collect();
        colours.sort_unstable();
        colours.dedup();
        assert!(colours.len() > 8, "the icon is one flat colour");
    }

    /// Every action has to be reachable, or it is a feature with no way in.
    #[test]
    fn the_menu_offers_every_action() {
        // Built without a message loop, which on Windows is legal for the menu
        // itself; if the notification area refuses the icon there is nothing to
        // assert about and the test says so rather than failing.
        let Ok(tray) = Tray::new(|_| {}) else {
            return;
        };
        assert_eq!(tray.len(), 5);

        let mut actions: Vec<_> = tray.ids.iter().map(|(_, a)| *a).collect();
        actions.sort_by_key(|a| format!("{a:?}"));
        actions.dedup();
        assert_eq!(actions.len(), 5, "two menu items run the same action");
    }
}
